{
 "title": "mirrord Operator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Client Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count by(fields_client_id, fields_client_name) (rate({namespace=\"mirrord\", service_name=\"mirrord-operator\"} | json | fields_message = `Session End` [$__auto]))"
    }
   ]
  },
  {
   "title": "User Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(count by(fields_client_id) (rate({namespace=\"mirrord\", service_name=\"mirrord-operator\"} | json | fields_client_id != `` [30d])))"
    }
   ]
  },
  {
   "title": "Target Sessions",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{namespace=\"mirrord\", service_name=\"mirrord-operator\"} | json | level =~ `INFO` | fields_target_type != `` | fields_target_name !~ `mirrord-copy-.*`"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{namespace=\"mirrord\", service_name=\"mirrord-operator\"} | json | level =~ `INFO` | fields_message != `Loaded license!`"
    }
   ]
  }
 ]
}