apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: metalmart
type: Opaque
stringData:
  postgres-password: "REPLACE_ME"
  catalogue-url: "REPLACE_ME"
  inventory-url: "REPLACE_ME"
  orders-url: "REPLACE_ME"
